name: client
description: Client application from Tocktec.com.br.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.5
  reorderables: ^0.6.0
  uuid: ^3.0.7
  mqtt_client: ^9.8.1
  amazon_cognito_identity_dart_2: ^3.3.0
  sleek_circular_slider: ^2.0.1
  tuple: ^2.0.1
  shared_preferences: ^2.1.0
  flutter_dotenv: ^5.0.2
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/1024x1024.png"
    background_color: "#28477D"
    theme_color: "#28477D"
  windows:
    generate: true
    image_path: "assets/images/1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/1024x1024.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
  